version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/hc/Desenvolvimento/Docker/Volumes/MongoDB:/data/db  
  app:
    container_name: app
    restart: always
    build: .
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    links:
      - mongo 