version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/hc/Desenvolvimento/Docker/Volumes/MongoDB:/data/db