version: '3.7'

services:
  app:
    container_name: app
    build: .
    ports:
      - "5858:5858"
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db